<?php
 $title = 'Add New Car';
 $this->headTitle($title);
 ?>
  <h1><?php echo $this->escapeHtml($title); ?></h1>
 
  <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('carros', array('action' => 'add')));
 $form->get('submit')->setAttribute('value', 'Add');
 $form->prepare();
  ?>
  
  <div class="panel panel-default">
  <div class="panel-body">
     
      <?= $this->form()->openTag($form); ?>
      <?= $this->formHidden($form->get('id')); ?>
 
      <div class="form-group">
         <?= $this->formRow($form->get('marca')); ?>
      </div>
      
      <div class="form-group">
      <?= $this->formRow($form->get('modelo')); ?>
      </div>
     
      <div class="form-group">
      <?= $this->formRow($form->get('motor')); ?>
      </div>
     
      <?= $this->formInput($form->get('submit')); ?>
      
      <?= $this->form()->closeTag($form); ?>
 
   </div>
 </div>