<?php
 $title = 'Edit Car';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $url = $this->url('carros', array('action' => 'edit', 'id' => $id));
 $form->setAttribute('action', $url);
 $form->get('submit')->setAttribute('value', 'Edit');
 $form->prepare();
 ?>
 
 <div class="panel panel-default">
 <div class="panel-body">
    
     <?= $this->form()->openTag($form); ?>
     <?= $this->formHidden($form->get('id')); ?>

     
     <div class="form-group">
        <?= $this->formRow($form->get('marca')); ?>
     </div>
     
     <div class="form-group">
     <?= $this->formRow($form->get('modelo')); ?>
     </div>
    
     <div class="form-group">
     <?= $this->formRow($form->get('motor')); ?>
     </div>
     
     <div class="row">
        <div class="col-md-4"><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeAlert">Remove</button></div>
        <div class="col-md-4 col-md-offset-4">
            <?= $this->formInput($form->get('submit')); ?>    
        </div>
     </div>
     
     <?= $this->form()->closeTag($form); ?>

  </div>
</div>


<div class="modal fade" id="removeAlert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Remove this Car?</h4>
      </div>
      <div class="modal-body">
        Are you sure?
        <?php $url = $this->url('carros', array('action' => 'delete', 'id' => $id)); ?>
      </div>
      <div class="modal-footer">
       <form action="<?= $url; ?>" method="POST">
            <input type="submit" class="btn btn-default" name="del" value="No" />
            <input type="submit" class="btn btn-danger" name="del" value="Yes" />
       </form>
      
      </div>
    </div>
  </div>
</div>