<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
<a href="http://zf2-tutorial.localhost/blog/add"><hr>Add</hr></a>


 <h1>My Blog</h1>

 <?php foreach ($this->posts as $post): ?>
 <article>
     <a href="http://zf2-tutorial.localhost/blog/edit/<?= $post->getId() ?>"><h1 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h1></a>
     <p>
         <?= $post->getText() ?>
     </p>
 </article>
 <?php endforeach ?>