<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Garagem\Module'                        => __DIR__ . '/Module.php',
    'Garagem\Controller\CarrosController' => __DIR__ . '/src/Garagem/Controller/CarrosController.php',
    'GaragemTest\Framework\TestCase'        => __DIR__ . '/tests/Garagem/Framework/TestCase.php',
    'GaragemTest\SampleTest'                => __DIR__ . '/tests/Garagem/SampleTest.php',
);
